AdaKutuphaneApp/Controllers/KitaplarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdaKutuphaneApp.Models.Entity;

namespace AdaKutuphaneApp.Controllers
{
    public class KitaplarController : Controller
    {
        // GET: Kitap
        AdaKutuphaneEntities1 db = new AdaKutuphaneEntities1();
        public ActionResult Index()
        {
            var kitaplar = db.tblKitaplar.ToList();
            return View(kitaplar);
        }

        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> kategorilist = (from i in db.tblKategoriler.Where(x => x.DURUM == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD,
                                               Value = i.ID.ToString()
                                           }).ToList();
            ViewBag.kategorisec = kategorilist;

            List<SelectListItem> yazarlist = (from i in db.tblYazarlar.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = i.AD + ' ' + i.SOYAD,
                                                    Value = i.ID.ToString()
                                                }).ToList();
            ViewBag.yazarsec = yazarlist;

            return View();

        }

        [HttpPost]
        public ActionResult KitapEkle(tblKitaplar k)
        {
            var kategorisec = db.tblKategoriler.Where(kategori => kategori.ID == k.tblKategoriler.ID).FirstOrDefault();
            var yazarsec = db.tblYazarlar.Where(yazar => yazar.ID == k.tblYazarlar.ID).FirstOrDefault();
            k.tblKategoriler = kategorisec;
            k.tblYazarlar = yazarsec;
            db.tblKitaplar.Add(k);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult KitapSil(int id)
        {
            var kitap = db.tblKitaplar.Find(id);
            db.tblKitaplar.Remove(kitap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KitapGetir(int id)
        {
            var kitap = db.tblKitaplar.Find(id);
            List<SelectListItem> kategorilist = (from i in db.tblKategoriler.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = i.AD,
                                                     Value = i.ID.ToString()
                                                 }).ToList();
            ViewBag.kategorisec = kategorilist;

            List<SelectListItem> yazarlist = (from i in db.tblYazarlar.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = i.AD + ' ' + i.SOYAD,
                                                  Value = i.ID.ToString()
                                              }).ToList();
            ViewBag.yazarsec = yazarlist;
            return View("KitapGetir", kitap);
        }

        public ActionResult KitapGuncelle(tblKitaplar k)
        {
            var kategorisec = db.tblKategoriler.Where(kategori => kategori.ID == k.tblKategoriler.ID).FirstOrDefault();
            var yazarsec = db.tblYazarlar.Where(yazar => yazar.ID == k.tblYazarlar.ID).FirstOrDefault();
            var kitap = db.tblKitaplar.Find(k.ID);
            kitap.AD = k.AD;
            kitap.KATEGORI = kategorisec.ID;
            kitap.YAZAR = yazarsec.ID;
            kitap.BASIMYILI = k.BASIMYILI;
            kitap.SAYFASAYISI = k.SAYFASAYISI;
            kitap.YAYINEVİ = k.YAYINEVİ;
            kitap.DURUM = k.DURUM;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

AdaKutuphaneApp/Views/Kitaplar/Index.cshtml
@using AdaKutuphaneApp.Models.Entity
@model List<tblKitaplar>
@{
    ViewBag.Title = "Kitap Listesi";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Kitaplar</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                    <li class="breadcrumb-item active">Kitaplar</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><button onclick="window.location.href='/Kitaplar/KitapEkle'" type="button" class="btn btn btn-primary"><i class="fas fa-edit"></i> Yeni Kitap Ekle</button></h3>
                    </div>
                    <div class="card-body">
                        <table id="datatable1" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th width="5%">ID</th>
                                    <th width="15%">Kitap Adı</th>
                                    <th width="15%">Kitap Yazarı</th>
                                    <th width="15%">Kategori</th>
                                    <th width="10%">Basım Yılı</th>
                                    <th width="10%">Yayınevi</th>
                                    <th width="5%">Sayfa</th>
                                    <th width="10%">Durum</th>
                                    <th width="15%">İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var kitap in Model)
                                {
                                    <tr>
                                        <td>@kitap.ID</td>
                                        <td>@kitap.AD</td>
                                        <td>@kitap.tblYazarlar.AD @kitap.tblYazarlar.SOYAD</td>
                                        <td>@kitap.tblKategoriler.AD</td>
                                        <td>@kitap.BASIMYILI</td>
                                        <td>@kitap.YAYINEVİ</td>
                                        <td>@kitap.SAYFASAYISI</td>
                                        <td>@kitap.DURUM</td>
                                        <td>
                                            <a href="/Kitaplar/KitapGetir/@kitap.ID" type="button" class="btn btn-sm btn-outline-primary"><i class="fas fa-edit"></i> Güncelle</a>
                                            @Html.ActionLink("Sil", "KitapSil", new { id = kitap.ID }, new { @class = "btn btn-sm btn-outline-danger", onclick = "return confirm('Silmek istediğinize emin misiniz?')" })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th width="5%">ID</th>
                                    <th width="15%">Kitap Adı</th>
                                    <th width="15%">Kitap Yazarı</th>
                                    <th width="15%">Kategori</th>
                                    <th width="10%">Basım Yılı</th>
                                    <th width="10%">Yayınevi</th>
                                    <th width="5%">Sayfa</th>
                                    <th width="10%">Durum</th>
                                    <th width="15%">İşlemler</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->

AdaKutuphaneApp/Views/Kitaplar/KitapEkle.cshtml
@model AdaKutuphaneApp.Models.Entity.tblKitaplar

@{
    ViewBag.Title = "Kitap Ekle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Kitap Ekle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Anasayfas</a></li>
                    <li class="breadcrumb-item active">Kitap Ekle</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Kitap Ekle</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form method="post">
                        <div class="card-body">
                            <div class="form-group">
                                <label>Kitap Adı</label>
                                @Html.TextBoxFor(kitap => kitap.AD, new { @class = "form-control", required = "required" })
                            </div>
                            <div class="form-group">
                                <label>Kategori</label>
                                @Html.DropDownListFor(kitap => kitap.tblKategoriler.ID, (List<SelectListItem>)ViewBag.kategorisec, "--- Kategori seçiniz ---", new { @class = "form-control select2", required = "required" })
                            </div>
                            <div class="form-group">
                                <label>Yazar</label>
                                @Html.DropDownListFor(kitap => kitap.tblYazarlar.ID, (List<SelectListItem>)ViewBag.yazarsec, "--- Yazar seçiniz ---", new { @class = "form-control select2", required = "required" })
                            </div>
                            <div class="form-group">
                                <label>Basım Yılı</label>
                                @Html.TextBoxFor(kitap => kitap.BASIMYILI, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Yayınevi</label>
                                @Html.TextBoxFor(kitap => kitap.YAYINEVİ, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Sayfa</label>
                                @Html.TextBoxFor(kitap => kitap.SAYFASAYISI, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Resim</label>
                                @Html.TextBoxFor(kitap => kitap.KITAPRESIM, new { @class = "form-control" })
                            </div>
                            <input type="hidden" name="DURUM" value="TRUE" />

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Kitap Ekle</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->


            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

AdaKutuphaneApp/Views/Kitaplar/KitapGetir.cshtml
@model AdaKutuphaneApp.Models.Entity.tblKitaplar
@{
    ViewBag.Title = "Kitap Güncelle";
    Layout = "~/Views/Shared/Layout.cshtml";
}


@using (Html.BeginForm("KitapGuncelle", "Kitaplar", FormMethod.Post))
{
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Kitap Güncelle</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Anasayfas</a></li>
                        <li class="breadcrumb-item active">Kitap Güncelle</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Kitap Güncelle</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Kitap ID</label>
                                    @Html.TextBoxFor(kitap => kitap.ID, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Kitap Adı</label>
                                    @Html.TextBoxFor(kitap => kitap.AD, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Kategori</label>
                                    @Html.DropDownListFor(kitap => kitap.tblKategoriler.ID, (List<SelectListItem>)ViewBag.kategorisec, "--- Kategori seçiniz ---", new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Yazar Adı</label>
                                    @Html.DropDownListFor(kitap => kitap.tblYazarlar.ID, (List<SelectListItem>)ViewBag.yazarsec, "--- Yazar seçiniz ---", new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Yazar Adı</label>
                                    @Html.TextBoxFor(kitap => kitap.BASIMYILI, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Yayınevi</label>
                                    @Html.TextBoxFor(kitap => kitap.YAYINEVİ, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Sayfa Sayısı</label>
                                    @Html.TextBoxFor(kitap => kitap.SAYFASAYISI, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Resim</label>
                                    @Html.TextBoxFor(kitap => kitap.KITAPRESIM, new { @class = "form-control" })
                                </div>
                                <input type="hidden" name="DURUM" value="TRUE" />
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Güncelle</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->


                </div>
                <!--/.col (left) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
}