AdaKutuphaneApp/Controllers/UyelerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdaKutuphaneApp.Models.Entity;

namespace AdaKutuphaneApp.Controllers
{
    public class UyelerController : Controller
    {
        // GET: Uyeler
        AdaKutuphaneEntities1 db = new AdaKutuphaneEntities1();

        public ActionResult Index()
        {
            var uyeler = db.tblUyeler.ToList();
            return View(uyeler);
        }

        [HttpGet]
        public ActionResult UyeEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UyeEkle(tblUyeler u)
        {
            if (!ModelState.IsValid)
            {
                return View("UyeEkle");
            }
            db.tblUyeler.Add(u);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UyeSil(int id)
        {
            var uye = db.tblUyeler.Find(id);
            db.tblUyeler.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UyeGetir(int id)
        {
            var uye = db.tblUyeler.Find(id);
            return View("UyeGetir", uye);
        }

        public ActionResult UyeGuncelle(tblUyeler u)
        {
            var uye = db.tblUyeler.Find(u.ID);
            uye.AD = u.AD;
            uye.SOYAD = u.SOYAD;
            uye.SOYAD = u.SOYAD;
            uye.MAIL = u.MAIL;
            uye.KULLANICIADI = u.KULLANICIADI;
            uye.PAROLA = u.PAROLA;
            uye.TELEFON = u.TELEFON;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult UyeKitapGecmis(int id)
        {
            var kitapgecmis = db.tblHareketler.Where(kitap => kitap.UYE == id).ToList();
            var uye = db.tblUyeler.Where(uyeid => uyeid.ID == id).Select(uyead => uyead.AD + " " + uyead.SOYAD).FirstOrDefault();
            ViewBag.uye = uye;
            return View(kitapgecmis);
        }
    }
}

AdaKutuphaneApp/Views/Uyeler/Index.cshtml
@using AdaKutuphaneApp.Models.Entity
@model List<tblUyeler>
@{
    ViewBag.Title = "Üye Listesi";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Üyeler</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                    <li class="breadcrumb-item active">Üyeler</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><button onclick="window.location.href='/Uyeler/UyeEkle'" type="button" class="btn btn btn-primary"><i class="fas fa-edit"></i> Yeni Üye Ekle</button></h3>
                    </div>
                    <div class="card-body">
                        <table id="datatable1" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th width="5%">ID</th>
                                    <th width="10%">Üye Adı</th>
                                    <th width="10%">Üye Soyadı</th>
                                    <th width="15%">Mail Adresi</th>
                                    <th width="10%">Kullanıcı Adı</th>
                                    <th width="10%">Parola</th>
                                    <th width="10%">Telefon</th>
                                    <th width="25%">İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var uye in Model)
                                {
                                    <tr>
                                        <td>@uye.ID</td>
                                        <td>@uye.AD</td>
                                        <td>@uye.SOYAD</td>
                                        <td>@uye.MAIL</td>
                                        <td>@uye.KULLANICIADI</td>
                                        <td>@uye.PAROLA</td>
                                        <td>@uye.TELEFON</td>

                                        <td>
                                            <a href="/Uyeler/UyeKitapGecmis/@uye.ID"><button type="button" class="btn btn-sm btn-outline-primary"><i class="fas fa-list"></i> Kitap Geçmişi</button></a>
                                            <a href="/Uyeler/UyeGetir/@uye.ID"><button type="button" class="btn btn-sm btn-outline-secondary"><i class="fas fa-edit"></i> Güncelle</button></a>
                                            @Html.ActionLink("Sil", "UyeSil", new { id = uye.ID }, new { @class = "btn btn-sm btn-outline-danger", onclick = "return confirm('Silmek istediğinize emin misiniz?')" })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Üye Adı</th>
                                    <th>Üye Soyadı</th>
                                    <th>Mail Adresi</th>
                                    <th>Kullanıcı Adı</th>
                                    <th>Parola</th>
                                    <th>Telefon</th>
                                    <th>İşlemler</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->

AdaKutuphaneApp/Views/Uyeler/UyeEkle.cshtml
@model AdaKutuphaneApp.Models.Entity.tblUyeler

@{
    ViewBag.Title = "Üye Ekle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Üye Ekle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Anasayfas</a></li>
                    <li class="breadcrumb-item active">Üye Ekle</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Üye Ekle</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form method="post">
                        <div class="card-body">
                            <div class="form-group">
                                <label>Üye Ad</label>
                                @Html.TextBoxFor(uye => uye.AD, new { @class = "form-control" })
                                @Html.ValidationMessageFor(uye => uye.AD, "", new { @span = "error invalid-feedback" })
                            </div>
                            <div class="form-group">
                                <label>Üye Soyad</label>
                                @Html.TextBoxFor(uye => uye.SOYAD, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Üye Mail</label>
                                @Html.TextBoxFor(uye => uye.MAIL, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Kullanıcı Adı</label>
                                @Html.TextBoxFor(uye => uye.KULLANICIADI, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Parola</label>
                                @Html.TextBoxFor(uye => uye.PAROLA, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label>Telefon</label>
                                @Html.TextBoxFor(uye => uye.TELEFON, new { @class = "form-control" })
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Kaydet</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->


            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

AdaKutuphaneApp/Views/Uyeler/UyeGetir.cshtml
@model AdaKutuphaneApp.Models.Entity.tblUyeler

@{
    ViewBag.Title = "Üye Güncelle";
    Layout = "~/Views/Shared/Layout.cshtml";
}


@using (Html.BeginForm("UyeGuncelle", "Uyeler", FormMethod.Post))
{
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Üye Güncelle</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Anasayfas</a></li>
                        <li class="breadcrumb-item active">Üye Güncelle</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Üye Güncelle</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Üye ID</label>
                                    @Html.TextBoxFor(uye => uye.ID, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Üye Adı</label>
                                    @Html.TextBoxFor(uye => uye.AD, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Üye Soyadı</label>
                                    @Html.TextBoxFor(uye => uye.SOYAD, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Mail Adresi</label>
                                    @Html.TextBoxFor(uye => uye.MAIL, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Kullanıcı Adı</label>
                                    @Html.TextBoxFor(uye => uye.KULLANICIADI, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Parola</label>
                                    @Html.TextBoxFor(uye => uye.PAROLA, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Üye Telefon</label>
                                    @Html.TextBoxFor(uye => uye.TELEFON, new { @class = "form-control" })
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Güncelle</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->


                </div>
                <!--/.col (left) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
}

AdaKutuphaneApp/Views/Uyeler/UyeKitapGecmis.cshtml
@using AdaKutuphaneApp.Models.Entity
@model List<tblHareketler>
@{
    ViewBag.Title = "Üye Kitap Geçmişi";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@ViewBag.Title</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><b>@ViewBag.uye</b> adlı üyenin kitap geçmişi</h3>
                    </div>
                    <div class="card-body">
                        <table id="datatable1" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th width="25%">Kitap Adı</th>
                                    <th width="25%">Personel</th>
                                    <th width="25%">Alış Tarihi</th>
                                    <th width="25%">İade Tarihi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var kitap in Model)
                                {
                                    <tr>
                                        <td>@kitap.tblKitaplar.AD</td>
                                        <td>@kitap.tblPersoneller.AD</td>
                                        <td>@Convert.ToDateTime(kitap.ALISTARIH).ToString("dd/MM/yyyy")</td>
                                        <td>@Convert.ToDateTime(kitap.IADETARIH).ToString("dd/MM/yyyy")</td>

                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th width="25%">Kitap Adı</th>
                                    <th width="25%">Personel</th>
                                    <th width="25%">Alış Tarihi</th>
                                    <th width="25%">İade Tarihi</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->