AdaKutuphaneApp/Controllers/YazarlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdaKutuphaneApp.Models.Entity;


namespace AdaKutuphaneApp.Controllers
{
    public class YazarlarController : Controller
    {
        // GET: Yazarlar
        AdaKutuphaneEntities1 db = new AdaKutuphaneEntities1();
        public ActionResult Index()
        {
            var yazarlar = db.tblYazarlar.ToList();
            return View(yazarlar);
        }

        [HttpGet]
        public ActionResult YazarEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YazarEkle(tblYazarlar y)
        {
            if (!ModelState.IsValid)
            {
                return View("YazarEKle");
            }
            db.tblYazarlar.Add(y);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult YazarSil(int id)
        {
            var yazar = db.tblYazarlar.Find(id);
            db.tblYazarlar.Remove(yazar);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult YazarGetir(int id)
        {
            var yazar = db.tblYazarlar.Find(id);
            return View("YazarGetir", yazar);
        }

        public ActionResult YazarGuncelle(tblYazarlar y)
        {
            var yazar = db.tblYazarlar.Find(y.ID);
            yazar.AD = y.AD;
            yazar.SOYAD = y.SOYAD;
            yazar.DETAY = y.DETAY;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult YazarKitaplar(int id)
        {
            var yazarkitaplari = db.tblKitaplar.Where(kitap => kitap.YAZAR == id).ToList();
            var yazar = db.tblYazarlar.Where(yazarid => yazarid.ID == id).Select(yazaradi => yazaradi.AD + " " + yazaradi.SOYAD).FirstOrDefault();
            ViewBag.yazar = yazar;
            return View(yazarkitaplari);
        }
    }
}

AdaKutuphaneApp/Views/Yazarlar/Index.cshtml
@using AdaKutuphaneApp.Models.Entity
@model List<tblYazarlar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Yazarlar</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                    <li class="breadcrumb-item active">Yazarlar</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><button onclick="window.location.href='/Yazarlar/YazarEkle'" type="button" class="btn btn btn-primary"><i class="fas fa-edit"></i> Yeni Yazar Ekle</button></h3>
                    </div>
                    <div class="card-body">
                        <table id="datatable1" data-page-length='25' class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th width="5%">ID</th>
                                    <th width="20%">Yazar Adı</th>
                                    <th width="20%">Yazar Soyadı</th>
                                    <th width="30%">Detay</th>
                                    <th width="25%">İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var yazar in Model)
                                {
                                    <tr>
                                        <td>@yazar.ID</td>
                                        <td>@yazar.AD</td>
                                        <td>@yazar.SOYAD</td>
                                        <td>@yazar.DETAY</td>
                                        <td>
                                            <button type="button" onclick="window.location.href='/Yazarlar/YazarKitaplar/@yazar.ID'" class="btn btn-sm btn-outline-primary"><i class="fas fa-edit"></i> Kitaplar</button>
                                            <button type="button" onclick="window.location.href='/Yazarlar/YazarGetir/@yazar.ID'" class="btn btn-sm btn-outline-secondary"><i class="fas fa-edit"></i> Güncelle</button>
                                            <button type="button" onclick="window.location.href='/Yazarlar/YazarSil/@yazar.ID'" class="btn btn-sm btn-outline-danger toastrDefaultSuccess"><i class="fas fa-trash-alt"></i> Sil</button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Yazar Adı</th>
                                    <th>Yazar Soyadı</th>
                                    <th>Detay</th>
                                    <th>İşlemler</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->

@section toasterscript {
    <script>
        $(function () {
            var Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000
            });

            $('.swalDefaultSuccess').click(function () {
                Toast.fire({
                    icon: 'success',
                    title: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.swalDefaultInfo').click(function () {
                Toast.fire({
                    icon: 'info',
                    title: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.swalDefaultError').click(function () {
                Toast.fire({
                    icon: 'error',
                    title: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.swalDefaultWarning').click(function () {
                Toast.fire({
                    icon: 'warning',
                    title: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.swalDefaultQuestion').click(function () {
                Toast.fire({
                    icon: 'question',
                    title: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });

            $('.toastrDefaultSuccess').click(function () {
                toastr.success('Lorem ipsum dolor sit amet, consetetur sadipscing elitr.')
            });
            $('.toastrDefaultInfo').click(function () {
                toastr.info('Lorem ipsum dolor sit amet, consetetur sadipscing elitr.')
            });
            $('.toastrDefaultError').click(function () {
                toastr.error('Lorem ipsum dolor sit amet, consetetur sadipscing elitr.')
            });
            $('.toastrDefaultWarning').click(function () {
                toastr.warning('Lorem ipsum dolor sit amet, consetetur sadipscing elitr.')
            });

            $('.toastsDefaultDefault').click(function () {
                $(document).Toasts('create', {
                    title: 'Toast Title',
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultTopLeft').click(function () {
                $(document).Toasts('create', {
                    title: 'Toast Title',
                    position: 'topLeft',
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultBottomRight').click(function () {
                $(document).Toasts('create', {
                    title: 'Toast Title',
                    position: 'bottomRight',
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultBottomLeft').click(function () {
                $(document).Toasts('create', {
                    title: 'Toast Title',
                    position: 'bottomLeft',
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultAutohide').click(function () {
                $(document).Toasts('create', {
                    title: 'Toast Title',
                    autohide: true,
                    delay: 750,
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultNotFixed').click(function () {
                $(document).Toasts('create', {
                    title: 'Toast Title',
                    fixed: false,
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultFull').click(function () {
                $(document).Toasts('create', {
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.',
                    title: 'Toast Title',
                    subtitle: 'Subtitle',
                    icon: 'fas fa-envelope fa-lg',
                })
            });
            $('.toastsDefaultFullImage').click(function () {
                $(document).Toasts('create', {
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.',
                    title: 'Toast Title',
                    subtitle: 'Subtitle',
                    image: '../../dist/img/user3-128x128.jpg',
                    imageAlt: 'User Picture',
                })
            });
            $('.toastsDefaultSuccess').click(function () {
                $(document).Toasts('create', {
                    class: 'bg-success',
                    title: 'Toast Title',
                    subtitle: 'Subtitle',
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultInfo').click(function () {
                $(document).Toasts('create', {
                    class: 'bg-info',
                    title: 'Toast Title',
                    subtitle: 'Subtitle',
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultWarning').click(function () {
                $(document).Toasts('create', {
                    class: 'bg-warning',
                    title: 'Toast Title',
                    subtitle: 'Subtitle',
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultDanger').click(function () {
                $(document).Toasts('create', {
                    class: 'bg-danger',
                    title: 'Toast Title',
                    subtitle: 'Subtitle',
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
            $('.toastsDefaultMaroon').click(function () {
                $(document).Toasts('create', {
                    class: 'bg-maroon',
                    title: 'Toast Title',
                    subtitle: 'Subtitle',
                    body: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr.'
                })
            });
        });
    </script>
}

AdaKutuphaneApp/Views/Yazarlar/YazarEkle.cshtml
@model AdaKutuphaneApp.Models.Entity.tblYazarlar
@{
    ViewBag.Title = "YazarEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Yazar Ekle</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Anasayfas</a></li>
                    <li class="breadcrumb-item active">Yazar Ekle</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Yazar Ekle</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form id="validateform" method="post">
                        <div class="card-body">
                            <div class="form-group">
                                <label>Yazar Ad</label>
                                @Html.TextBoxFor(yazar => yazar.AD, new { @class = "form-control", @placeholder = "Yazar Adı" })
                                @Html.ValidationMessageFor(yazar => yazar.AD, "", new { @class = "text-xs text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Yazar Soyad</label>
                                @Html.TextBoxFor(yazar => yazar.SOYAD, new { @class = "form-control", @placeholder = "Yazar Soyadı" })
                                @Html.ValidationMessageFor(yazar => yazar.SOYAD, "", new { @class = "text-xs text-danger" })
                            </div>
                            <div class="form-group">
                                <label>Detay</label>
                                @Html.TextAreaFor(yazar => yazar.DETAY, new { @class = "form-control" })
                            </div>

                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Kaydet</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->


            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

@section scripts {
    <script>
        $(function () {
            $('#validateform').validate({
                rules: {
                    AD: {
                        required: true,
                        minlength: 2,
                        maxlength: 20,
                    },

                    SOYAD: {
                        required: true,
                        minlength: 2,
                        maxlength:20,
                    },

                },
                messages: {
                    AD: {
                        required: "Lütfen ad giriniz",
                        minlength: "Ad alanı en az 2 hane olmalıdır",
                        maxlength: "Ad en fazla 20 karakter olmalıdır",
                    },

                    SOYAD: {
                        required: "Lütfen soyad giriniz",
                        minlength: "Soyad alanı en az 2 hane olmalıdır",
                        maxlength: "Ad en fazla 20 karakter olmalıdır",

                    }
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        });
    </script>
}

AdaKutuphaneApp/Views/Yazarlar/YazarGetir.cshtml
@model AdaKutuphaneApp.Models.Entity.tblYazarlar
@{
    ViewBag.Title = "YazarGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("YazarGuncelle", "Yazarlar", FormMethod.Post))
{
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yazar Güncelle</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Anasayfas</a></li>
                        <li class="breadcrumb-item active">Yazar Güncelle</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Yazar Güncelle</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form method="post">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="KategoriID">Yazar ID</label>
                                    @Html.TextBoxFor(yazar => yazar.ID, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label for="YazarAd">Yazar Adı</label>
                                    @Html.TextBoxFor(yazar => yazar.AD, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label for="YazarSoyad">Yazar Soyadı</label>
                                    @Html.TextBoxFor(yazar => yazar.SOYAD, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label for="Detay">Detay</label>
                                    @Html.TextAreaFor(yazar => yazar.DETAY, new { @class = "form-control" })
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Güncelle</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->


                </div>
                <!--/.col (left) -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
}

AdaKutuphaneApp/Views/Yazarlar/YazarKitaplar.cshtml
@using AdaKutuphaneApp.Models.Entity;
@model List<tblKitaplar>

@{
    ViewBag.Title = "YazarKitaplar";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Yazarlar</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Anasayfa</a></li>
                    <li class="breadcrumb-item active">Yazarlar</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><button onclick="window.location.href='/Kitaplar/KitapEkle'" type="button" class="btn btn btn-primary"><i class="fas fa-edit"></i> Yeni Kitap Ekle</button></h3>
                    </div>
                    <div class="card-body">
                        <table id="datatable1" data-page-length='25' class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th width="5%">ID</th>
                                    <th width="20%">Kitap Adı</th>
                                    <th width="20%">Kategori</th>
                                    <th width="40%">Yayınevi</th>
                                    <th width="15%">İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var kitap in Model)
                                {
                                    <tr>
                                        <td>@kitap.ID</td>
                                        <td>@kitap.AD</td>
                                        <td>@kitap.tblKategoriler.AD</td>
                                        <td>@kitap.YAYINEVİ</td>
                                        <td>
                                            <button type="button" onclick="window.location.href='/Kitaplar/KitapGetir/@kitap.ID'" class="btn btn-sm btn-outline-primary"><i class="fas fa-edit"></i> Güncelle</button>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Yazar Adı</th>
                                    <th>Yazar Soyadı</th>
                                    <th>Detay</th>
                                    <th>İşlemler</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->