AdaKutuphaneApp/Controllers/OgrenciPaneliController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdaKutuphaneApp.Models.Entity;


namespace AdaKutuphaneApp.Controllers
{
    public class OgrenciPaneliController : Controller
    {
        // GET: OgrenciPaneli
        AdaKutuphaneEntities1 db = new AdaKutuphaneEntities1();
        [HttpGet]
        [Authorize]
        public ActionResult Index()
        {
            var uyemail = (string)Session["Mail"];
            var bilgiler = db.tblUyeler.FirstOrDefault(x => x.MAIL == uyemail);
            return View(bilgiler);
        }
        [HttpPost]
        public ActionResult Index(tblUyeler p)
        {
            var kullanici = (string)Session["Mail"];
            var uye = db.tblUyeler.FirstOrDefault(x => x.MAIL == kullanici);
            uye.PAROLA = p.PAROLA;
            db.SaveChanges();
            return View();
        }
    }
}

AdaKutuphaneApp/Views/OgrenciPaneli/Index.cshtml
@model AdaKutuphaneApp.Models.Entity.tblUyeler
@{
    ViewBag.Title = "Öğrenci Paneli";
    Layout = "~/Views/Shared/_OPanelLayout.cshtml";

}


<div class="container-fluid">
    <h1 class="mt-4">Profilim</h1>
    @using (Html.BeginForm("Index", "OgrenciPaneli", FormMethod.Post))
    {
        <table class="table table-hover">
            <tr>
                <td>
                    Ad: @Html.TextBoxFor(x => x.AD, new { @class = "form-control", @readonly = "readonly", @Name = "AD" })
                </td>
            </tr>
            <tr>
                <td>
                    Soyad: @Html.TextBoxFor(x => x.SOYAD, new { @class = "form-control", @readonly = "readonly", @Name = "SOYAD" })
                </td>
            </tr>
            <tr>
                <td>
                    E-Posta: @Html.TextBoxFor(x => x.MAIL, new { @class = "form-control", @readonly = "readonly", @Name = "MAIL" })
                </td>
            </tr>
            <tr>
                <td>
                    Kullanıcı Adı: @Html.TextBoxFor(x => x.KULLANICIADI, new { @class = "form-control", @readonly = "readonly", @Name = "KULLANICIADI" })
                </td>
            </tr>
            <tr>
                <td>
                    Şifre: @Html.TextBoxFor(x => x.PAROLA, new { @class = "form-control", @Name = "PAROLA" })
                </td>
            </tr>
            <tr>
                <td>
                    <button class="btn btn-warning">Bilgileri Güncelle</button>
                </td>
            </tr>
        </table>
    }
</div>